version: 2
updates:
  - package-ecosystem: nuget
    directory: "/dotnet"
    schedule:
      interval: weekly
      time: "04:00"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    groups:
      egui-stack:
        patterns:
          - "eframe"
          - "egui"
          - "egui*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
